repos:
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8
        args:
          - --max-line-length=88
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        args: [--ignore-missing-imports, --disable-error-code=union-attr, --disable-error-code=override,
               --disable-error-code=attr-defined, --disable-error-code=arg-type, --disable-error-code=str-bytes-safe,
               --disable-error-code=return-value, --disable-error-code=return, --disable-error-code=unused-coroutine
        ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort
        args:
          - '--profile'
          - 'black'
          - '--skip-glob'
          - '**/migrations/*'
          - '--skip-glob'
          - '**/__init__.py'
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        args: ['--line-length', '88']